### ISSUE TITLE
'You must make your stub callable' - confusion

### ISSUE THREAD

**Issue by paul-hammant** [blaix/tdubs#11]
You must make the methods on your stub callable?  "The stub" is shorthand for the-stubbed-class - right?

Re:

```
calling(prompter).passing('Last name:').returns('Blake')
```

The example code contains a class Greeter, which has a method greet(greeting), yet examples on setting up stubs in the same code fragment do not refer to 'greet' as a method again. This newbie is lost, and I'm adept with JMock 1 & 2, Java's Mockito so am super comfortable with the science.

**Comment by blaix** [comment]
> "The stub" is shorthand for the-stubbed-class - right?

No, it's shorthand for the-stubbed-object. That object could be a class, an instance of a class, a function, or anything.

In the example, I'm testing a `greeter` method of the `Greeting` class. It has some dependencies passed in, like the prompter. In the production code, the prompter is a real callable. In the tests, it is a stub that I have made callable.

Does that clear it up?

**Comment by blaix** [comment]
Please re-open if there's still confusion.
