### ISSUE TITLE
Does the calling().passing().returns() syntax work with mocks too? 

### ISSUE THREAD

**Issue by paul-hammant** [blaix/tdubs#12]
```
calling(myclass.method_one).passing(u'string-param').returns(0)
```

Is returning a Mock into the thing that was doing myinstance.method_one('string-param') when I expected it so return 0 (zero).

Mock is an extension of Stub (that fact is hinted at in the documentation) - I should have all the behaviors of the super class - no ?

**Comment by blaix** [comment]
> Does the calling().passing().returns() syntax work with mocks too?

Yes, everything a stub can do, a mock can do too.
