### ISSUE TITLE
verify_no_more_invocations 

### ISSUE THREAD

**Issue by paul-hammant** [blaix/tdubs#13]
verify_no_more_invocations needed please, like Mockito:

http://mockito.googlecode.com/hg-history/1.5/javadoc/org/mockito/Mockito.html#verifyNoMoreInteractions%28java.lang.Object...%29

Apart from anything else, you use this to reverse engineer the things you have to mock.

**Comment by blaix** [comment]
I can't imagine a scenario where I'd want to do this. Can you give me an example?

**Comment by blaix** [comment]
> reverse engineer the things you have to mock

To do this, I'd use a `Stub`, which will raise for any call you haven't explicitly defined as allowed.

**Comment by blaix** [comment]
No plans to add this right now.
